CREATE DATABASE teste;
CREATE DATABASE sucos;
use sucos;
DROP DATABASE TESTE;
CREATE TABLE tb_clientes
( CPF VARCHAR (11) ,
NOME VARCHAR (100) ,
ENDERECO1 VARCHAR (150) ,
ENDERECO2 VARCHAR (150) ,
BAIRRO VARCHAR (50) ,
CIDADE VARCHAR (50) ,
ESTADO VARCHAR (2) ,
CEP VARCHAR (8) ,
IDADE INT,
SEXO VARCHAR (1) ,
LIMITE_CREDITO FLOAT ,
VOLUME_COMPRA FLOAT ,
PRIMEIRA_COMPRA BOOL );
DROP TABLE tb_clientes_v2;
create table tbproduto
(
PRODUTO varchar(30),
NOME varchar(100),
EMBALAGEM VARCHAR (50),
TAMANHO VARCHAR (50),
SABOR VARCHAR (50),
PRECO_LISTA FLOAT
);
INSERT INTO tbproduto (
PRODUTO,
NOME, 
EMBALAGEM, 
TAMANHO,
SABOR,
PRECO_LISTA) VALUES (
'1004327', 'Videira do Campo - 1,5 Litros - Melancia', 'PET', '1,5 Litros', 'Melancia', 19.51);

SELECT * FROM tbproduto;

SELECT * FROM tbproduto where nome LIKE '%ml%';

UPDATE tbproduto SET EMBALAGEM = 'Lata', TAMANHO = '350 ml' where PRODUTO = '1000889';

DELETE from tbproduto where PRODUTO = '1000889';
